apiVersion: v1
data:
  prometheus.yml: |
    global:
      evaluation_interval: 5s
      scrape_interval: 5s
      scrape_timeout: 5s
    scrape_configs:
    - job_name: 'sriov-metrics'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_target]
        action: keep
        regex: true
      static_configs:
      - targets: ['sriov-metrics-exporter.monitoring.svc.cluster.local']
      scheme: http
    - job_name: 'sriov-metrics-standalone'
      scheme: http
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: ^(.*):\d+$
        target_label: __address__
        replacement: $1:9999
      - target_label: __scheme__
        replacement: http
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: prometheus
    component: server
  name: minimum-scrape-config-sriov-exporter.yml 
  namespace: monitoring
